<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>swarm_msgs</name>
  <version>0.1.0</version>
  <description>Custom Message for swarm tools</description>
  <maintainer email="yamazumi.mitsuhiro@gmail.com">Mitsuhiro Yamazumi</maintainer>
  <license>MIT</license>

  <!-- ビルドツールの依存関係 -->
  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- メッセージの生成と使用に必要な依存関係 -->
  <build_depend>rosidl_default_generators</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>geometry_msgs</build_depend>

  <!-- 実行時に必要な依存関係 -->
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- メッセージパッケージのグループ所属 -->
  <member_of_group>rosidl_interface_packages</member_of_group>

  <!-- テスト依存関係 -->
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
